// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: bibd/v1/discovery.proto

package bibv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PeerCandidate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PeerId        string                 `protobuf:"bytes,1,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	Multiaddrs    []string               `protobuf:"bytes,2,rep,name=multiaddrs,proto3" json:"multiaddrs,omitempty"`
	Score         float64                `protobuf:"fixed64,3,opt,name=score,proto3" json:"score,omitempty"`
	LastRttMs     float64                `protobuf:"fixed64,4,opt,name=last_rtt_ms,json=lastRttMs,proto3" json:"last_rtt_ms,omitempty"`
	Load          float64                `protobuf:"fixed64,5,opt,name=load,proto3" json:"load,omitempty"`
	Region        string                 `protobuf:"bytes,6,opt,name=region,proto3" json:"region,omitempty"`
	Tags          []string               `protobuf:"bytes,7,rep,name=tags,proto3" json:"tags,omitempty"`
	Source        string                 `protobuf:"bytes,8,opt,name=source,proto3" json:"source,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeerCandidate) Reset() {
	*x = PeerCandidate{}
	mi := &file_bibd_v1_discovery_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerCandidate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerCandidate) ProtoMessage() {}

func (x *PeerCandidate) ProtoReflect() protoreflect.Message {
	mi := &file_bibd_v1_discovery_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerCandidate.ProtoReflect.Descriptor instead.
func (*PeerCandidate) Descriptor() ([]byte, []int) {
	return file_bibd_v1_discovery_proto_rawDescGZIP(), []int{0}
}

func (x *PeerCandidate) GetPeerId() string {
	if x != nil {
		return x.PeerId
	}
	return ""
}

func (x *PeerCandidate) GetMultiaddrs() []string {
	if x != nil {
		return x.Multiaddrs
	}
	return nil
}

func (x *PeerCandidate) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *PeerCandidate) GetLastRttMs() float64 {
	if x != nil {
		return x.LastRttMs
	}
	return 0
}

func (x *PeerCandidate) GetLoad() float64 {
	if x != nil {
		return x.Load
	}
	return 0
}

func (x *PeerCandidate) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *PeerCandidate) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *PeerCandidate) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

type FindCandidatesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         uint32                 `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`                                  // Max candidates to return (default 10)
	PreferRegion  string                 `protobuf:"bytes,2,opt,name=prefer_region,json=preferRegion,proto3" json:"prefer_region,omitempty"` // Optional region preference
	PreferTags    []string               `protobuf:"bytes,3,rep,name=prefer_tags,json=preferTags,proto3" json:"prefer_tags,omitempty"`       // Optional tag preferences
	IncludeSelf   bool                   `protobuf:"varint,4,opt,name=include_self,json=includeSelf,proto3" json:"include_self,omitempty"`   // optionally include the local daemon as a candidate
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindCandidatesRequest) Reset() {
	*x = FindCandidatesRequest{}
	mi := &file_bibd_v1_discovery_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindCandidatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindCandidatesRequest) ProtoMessage() {}

func (x *FindCandidatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bibd_v1_discovery_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindCandidatesRequest.ProtoReflect.Descriptor instead.
func (*FindCandidatesRequest) Descriptor() ([]byte, []int) {
	return file_bibd_v1_discovery_proto_rawDescGZIP(), []int{1}
}

func (x *FindCandidatesRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *FindCandidatesRequest) GetPreferRegion() string {
	if x != nil {
		return x.PreferRegion
	}
	return ""
}

func (x *FindCandidatesRequest) GetPreferTags() []string {
	if x != nil {
		return x.PreferTags
	}
	return nil
}

func (x *FindCandidatesRequest) GetIncludeSelf() bool {
	if x != nil {
		return x.IncludeSelf
	}
	return false
}

type FindCandidatesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Candidates    []*PeerCandidate       `protobuf:"bytes,1,rep,name=candidates,proto3" json:"candidates,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindCandidatesResponse) Reset() {
	*x = FindCandidatesResponse{}
	mi := &file_bibd_v1_discovery_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindCandidatesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindCandidatesResponse) ProtoMessage() {}

func (x *FindCandidatesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bibd_v1_discovery_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindCandidatesResponse.ProtoReflect.Descriptor instead.
func (*FindCandidatesResponse) Descriptor() ([]byte, []int) {
	return file_bibd_v1_discovery_proto_rawDescGZIP(), []int{2}
}

func (x *FindCandidatesResponse) GetCandidates() []*PeerCandidate {
	if x != nil {
		return x.Candidates
	}
	return nil
}

var File_bibd_v1_discovery_proto protoreflect.FileDescriptor

const file_bibd_v1_discovery_proto_rawDesc = "" +
	"\n" +
	"\x17bibd/v1/discovery.proto\x12\abibd.v1\"\xd6\x01\n" +
	"\rPeerCandidate\x12\x17\n" +
	"\apeer_id\x18\x01 \x01(\tR\x06peerId\x12\x1e\n" +
	"\n" +
	"multiaddrs\x18\x02 \x03(\tR\n" +
	"multiaddrs\x12\x14\n" +
	"\x05score\x18\x03 \x01(\x01R\x05score\x12\x1e\n" +
	"\vlast_rtt_ms\x18\x04 \x01(\x01R\tlastRttMs\x12\x12\n" +
	"\x04load\x18\x05 \x01(\x01R\x04load\x12\x16\n" +
	"\x06region\x18\x06 \x01(\tR\x06region\x12\x12\n" +
	"\x04tags\x18\a \x03(\tR\x04tags\x12\x16\n" +
	"\x06source\x18\b \x01(\tR\x06source\"\x96\x01\n" +
	"\x15FindCandidatesRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\rR\x05limit\x12#\n" +
	"\rprefer_region\x18\x02 \x01(\tR\fpreferRegion\x12\x1f\n" +
	"\vprefer_tags\x18\x03 \x03(\tR\n" +
	"preferTags\x12!\n" +
	"\finclude_self\x18\x04 \x01(\bR\vincludeSelf\"P\n" +
	"\x16FindCandidatesResponse\x126\n" +
	"\n" +
	"candidates\x18\x01 \x03(\v2\x16.bibd.v1.PeerCandidateR\n" +
	"candidates2^\n" +
	"\tDiscovery\x12Q\n" +
	"\x0eFindCandidates\x12\x1e.bibd.v1.FindCandidatesRequest\x1a\x1f.bibd.v1.FindCandidatesResponseB3Z1github.com/bencoepp/bib/internal/pb/bibd/v1;bibv1b\x06proto3"

var (
	file_bibd_v1_discovery_proto_rawDescOnce sync.Once
	file_bibd_v1_discovery_proto_rawDescData []byte
)

func file_bibd_v1_discovery_proto_rawDescGZIP() []byte {
	file_bibd_v1_discovery_proto_rawDescOnce.Do(func() {
		file_bibd_v1_discovery_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_bibd_v1_discovery_proto_rawDesc), len(file_bibd_v1_discovery_proto_rawDesc)))
	})
	return file_bibd_v1_discovery_proto_rawDescData
}

var file_bibd_v1_discovery_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_bibd_v1_discovery_proto_goTypes = []any{
	(*PeerCandidate)(nil),          // 0: bibd.v1.PeerCandidate
	(*FindCandidatesRequest)(nil),  // 1: bibd.v1.FindCandidatesRequest
	(*FindCandidatesResponse)(nil), // 2: bibd.v1.FindCandidatesResponse
}
var file_bibd_v1_discovery_proto_depIdxs = []int32{
	0, // 0: bibd.v1.FindCandidatesResponse.candidates:type_name -> bibd.v1.PeerCandidate
	1, // 1: bibd.v1.Discovery.FindCandidates:input_type -> bibd.v1.FindCandidatesRequest
	2, // 2: bibd.v1.Discovery.FindCandidates:output_type -> bibd.v1.FindCandidatesResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_bibd_v1_discovery_proto_init() }
func file_bibd_v1_discovery_proto_init() {
	if File_bibd_v1_discovery_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_bibd_v1_discovery_proto_rawDesc), len(file_bibd_v1_discovery_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_bibd_v1_discovery_proto_goTypes,
		DependencyIndexes: file_bibd_v1_discovery_proto_depIdxs,
		MessageInfos:      file_bibd_v1_discovery_proto_msgTypes,
	}.Build()
	File_bibd_v1_discovery_proto = out.File
	file_bibd_v1_discovery_proto_goTypes = nil
	file_bibd_v1_discovery_proto_depIdxs = nil
}
