// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: bibd/v1/identitiy.proto

package bibv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	IdentityService_PublishIdentity_FullMethodName    = "/bibd.v1.IdentityService/PublishIdentity"
	IdentityService_RetrieveIdentity_FullMethodName   = "/bibd.v1.IdentityService/RetrieveIdentity"
	IdentityService_RetrieveIdentities_FullMethodName = "/bibd.v1.IdentityService/RetrieveIdentities"
	IdentityService_SubmitRotationLink_FullMethodName = "/bibd.v1.IdentityService/SubmitRotationLink"
	IdentityService_GetLogRoot_FullMethodName         = "/bibd.v1.IdentityService/GetLogRoot"
	IdentityService_GetSelfIdentity_FullMethodName    = "/bibd.v1.IdentityService/GetSelfIdentity"
)

// IdentityServiceClient is the client API for IdentityService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Service definition
type IdentityServiceClient interface {
	PublishIdentity(ctx context.Context, in *PublishIdentityRequest, opts ...grpc.CallOption) (*PublishIdentityResponse, error)
	RetrieveIdentity(ctx context.Context, in *RetrieveIdentityRequest, opts ...grpc.CallOption) (*RetrieveIdentityResponse, error)
	RetrieveIdentities(ctx context.Context, in *RetrieveIdentitiesRequest, opts ...grpc.CallOption) (*RetrieveIdentitiesResponse, error)
	SubmitRotationLink(ctx context.Context, in *SubmitRotationLinkRequest, opts ...grpc.CallOption) (*SubmitRotationLinkResponse, error)
	GetLogRoot(ctx context.Context, in *GetLogRootRequest, opts ...grpc.CallOption) (*GetLogRootResponse, error)
	GetSelfIdentity(ctx context.Context, in *GetSelfIdentityRequest, opts ...grpc.CallOption) (*GetSelfIdentityResponse, error)
}

type identityServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewIdentityServiceClient(cc grpc.ClientConnInterface) IdentityServiceClient {
	return &identityServiceClient{cc}
}

func (c *identityServiceClient) PublishIdentity(ctx context.Context, in *PublishIdentityRequest, opts ...grpc.CallOption) (*PublishIdentityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PublishIdentityResponse)
	err := c.cc.Invoke(ctx, IdentityService_PublishIdentity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityServiceClient) RetrieveIdentity(ctx context.Context, in *RetrieveIdentityRequest, opts ...grpc.CallOption) (*RetrieveIdentityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RetrieveIdentityResponse)
	err := c.cc.Invoke(ctx, IdentityService_RetrieveIdentity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityServiceClient) RetrieveIdentities(ctx context.Context, in *RetrieveIdentitiesRequest, opts ...grpc.CallOption) (*RetrieveIdentitiesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RetrieveIdentitiesResponse)
	err := c.cc.Invoke(ctx, IdentityService_RetrieveIdentities_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityServiceClient) SubmitRotationLink(ctx context.Context, in *SubmitRotationLinkRequest, opts ...grpc.CallOption) (*SubmitRotationLinkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubmitRotationLinkResponse)
	err := c.cc.Invoke(ctx, IdentityService_SubmitRotationLink_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityServiceClient) GetLogRoot(ctx context.Context, in *GetLogRootRequest, opts ...grpc.CallOption) (*GetLogRootResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetLogRootResponse)
	err := c.cc.Invoke(ctx, IdentityService_GetLogRoot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityServiceClient) GetSelfIdentity(ctx context.Context, in *GetSelfIdentityRequest, opts ...grpc.CallOption) (*GetSelfIdentityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSelfIdentityResponse)
	err := c.cc.Invoke(ctx, IdentityService_GetSelfIdentity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IdentityServiceServer is the server API for IdentityService service.
// All implementations must embed UnimplementedIdentityServiceServer
// for forward compatibility.
//
// Service definition
type IdentityServiceServer interface {
	PublishIdentity(context.Context, *PublishIdentityRequest) (*PublishIdentityResponse, error)
	RetrieveIdentity(context.Context, *RetrieveIdentityRequest) (*RetrieveIdentityResponse, error)
	RetrieveIdentities(context.Context, *RetrieveIdentitiesRequest) (*RetrieveIdentitiesResponse, error)
	SubmitRotationLink(context.Context, *SubmitRotationLinkRequest) (*SubmitRotationLinkResponse, error)
	GetLogRoot(context.Context, *GetLogRootRequest) (*GetLogRootResponse, error)
	GetSelfIdentity(context.Context, *GetSelfIdentityRequest) (*GetSelfIdentityResponse, error)
	mustEmbedUnimplementedIdentityServiceServer()
}

// UnimplementedIdentityServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedIdentityServiceServer struct{}

func (UnimplementedIdentityServiceServer) PublishIdentity(context.Context, *PublishIdentityRequest) (*PublishIdentityResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PublishIdentity not implemented")
}
func (UnimplementedIdentityServiceServer) RetrieveIdentity(context.Context, *RetrieveIdentityRequest) (*RetrieveIdentityResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RetrieveIdentity not implemented")
}
func (UnimplementedIdentityServiceServer) RetrieveIdentities(context.Context, *RetrieveIdentitiesRequest) (*RetrieveIdentitiesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RetrieveIdentities not implemented")
}
func (UnimplementedIdentityServiceServer) SubmitRotationLink(context.Context, *SubmitRotationLinkRequest) (*SubmitRotationLinkResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitRotationLink not implemented")
}
func (UnimplementedIdentityServiceServer) GetLogRoot(context.Context, *GetLogRootRequest) (*GetLogRootResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLogRoot not implemented")
}
func (UnimplementedIdentityServiceServer) GetSelfIdentity(context.Context, *GetSelfIdentityRequest) (*GetSelfIdentityResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSelfIdentity not implemented")
}
func (UnimplementedIdentityServiceServer) mustEmbedUnimplementedIdentityServiceServer() {}
func (UnimplementedIdentityServiceServer) testEmbeddedByValue()                         {}

// UnsafeIdentityServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IdentityServiceServer will
// result in compilation errors.
type UnsafeIdentityServiceServer interface {
	mustEmbedUnimplementedIdentityServiceServer()
}

func RegisterIdentityServiceServer(s grpc.ServiceRegistrar, srv IdentityServiceServer) {
	// If the following call pancis, it indicates UnimplementedIdentityServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&IdentityService_ServiceDesc, srv)
}

func _IdentityService_PublishIdentity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublishIdentityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityServiceServer).PublishIdentity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentityService_PublishIdentity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityServiceServer).PublishIdentity(ctx, req.(*PublishIdentityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdentityService_RetrieveIdentity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RetrieveIdentityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityServiceServer).RetrieveIdentity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentityService_RetrieveIdentity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityServiceServer).RetrieveIdentity(ctx, req.(*RetrieveIdentityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdentityService_RetrieveIdentities_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RetrieveIdentitiesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityServiceServer).RetrieveIdentities(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentityService_RetrieveIdentities_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityServiceServer).RetrieveIdentities(ctx, req.(*RetrieveIdentitiesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdentityService_SubmitRotationLink_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitRotationLinkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityServiceServer).SubmitRotationLink(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentityService_SubmitRotationLink_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityServiceServer).SubmitRotationLink(ctx, req.(*SubmitRotationLinkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdentityService_GetLogRoot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLogRootRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityServiceServer).GetLogRoot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentityService_GetLogRoot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityServiceServer).GetLogRoot(ctx, req.(*GetLogRootRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdentityService_GetSelfIdentity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSelfIdentityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityServiceServer).GetSelfIdentity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentityService_GetSelfIdentity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityServiceServer).GetSelfIdentity(ctx, req.(*GetSelfIdentityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// IdentityService_ServiceDesc is the grpc.ServiceDesc for IdentityService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var IdentityService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "bibd.v1.IdentityService",
	HandlerType: (*IdentityServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PublishIdentity",
			Handler:    _IdentityService_PublishIdentity_Handler,
		},
		{
			MethodName: "RetrieveIdentity",
			Handler:    _IdentityService_RetrieveIdentity_Handler,
		},
		{
			MethodName: "RetrieveIdentities",
			Handler:    _IdentityService_RetrieveIdentities_Handler,
		},
		{
			MethodName: "SubmitRotationLink",
			Handler:    _IdentityService_SubmitRotationLink_Handler,
		},
		{
			MethodName: "GetLogRoot",
			Handler:    _IdentityService_GetLogRoot_Handler,
		},
		{
			MethodName: "GetSelfIdentity",
			Handler:    _IdentityService_GetSelfIdentity_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "bibd/v1/identitiy.proto",
}
