// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: bibd/v1/identitiy.proto

package bibv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IdentityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IdentityRequest) Reset() {
	*x = IdentityRequest{}
	mi := &file_bibd_v1_identitiy_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IdentityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdentityRequest) ProtoMessage() {}

func (x *IdentityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bibd_v1_identitiy_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdentityRequest.ProtoReflect.Descriptor instead.
func (*IdentityRequest) Descriptor() ([]byte, []int) {
	return file_bibd_v1_identitiy_proto_rawDescGZIP(), []int{0}
}

type IdentityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IdentityResponse) Reset() {
	*x = IdentityResponse{}
	mi := &file_bibd_v1_identitiy_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IdentityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdentityResponse) ProtoMessage() {}

func (x *IdentityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bibd_v1_identitiy_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdentityResponse.ProtoReflect.Descriptor instead.
func (*IdentityResponse) Descriptor() ([]byte, []int) {
	return file_bibd_v1_identitiy_proto_rawDescGZIP(), []int{1}
}

type ListIdentitiesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListIdentitiesRequest) Reset() {
	*x = ListIdentitiesRequest{}
	mi := &file_bibd_v1_identitiy_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListIdentitiesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListIdentitiesRequest) ProtoMessage() {}

func (x *ListIdentitiesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bibd_v1_identitiy_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListIdentitiesRequest.ProtoReflect.Descriptor instead.
func (*ListIdentitiesRequest) Descriptor() ([]byte, []int) {
	return file_bibd_v1_identitiy_proto_rawDescGZIP(), []int{2}
}

type ListIdentitiesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Identities    []*IdentityResponse    `protobuf:"bytes,1,rep,name=identities,proto3" json:"identities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListIdentitiesResponse) Reset() {
	*x = ListIdentitiesResponse{}
	mi := &file_bibd_v1_identitiy_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListIdentitiesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListIdentitiesResponse) ProtoMessage() {}

func (x *ListIdentitiesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bibd_v1_identitiy_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListIdentitiesResponse.ProtoReflect.Descriptor instead.
func (*ListIdentitiesResponse) Descriptor() ([]byte, []int) {
	return file_bibd_v1_identitiy_proto_rawDescGZIP(), []int{3}
}

func (x *ListIdentitiesResponse) GetIdentities() []*IdentityResponse {
	if x != nil {
		return x.Identities
	}
	return nil
}

var File_bibd_v1_identitiy_proto protoreflect.FileDescriptor

const file_bibd_v1_identitiy_proto_rawDesc = "" +
	"\n" +
	"\x17bibd/v1/identitiy.proto\x12\abibd.v1\"\x11\n" +
	"\x0fIdentityRequest\"\x12\n" +
	"\x10IdentityResponse\"\x17\n" +
	"\x15ListIdentitiesRequest\"S\n" +
	"\x16ListIdentitiesResponse\x129\n" +
	"\n" +
	"identities\x18\x01 \x03(\v2\x19.bibd.v1.IdentityResponseR\n" +
	"identities2\xc1\x02\n" +
	"\x0fIdentityService\x12G\n" +
	"\x10RegisterIdentity\x12\x18.bibd.v1.IdentityRequest\x1a\x19.bibd.v1.IdentityResponse\x12G\n" +
	"\x10RetrieveIdentity\x12\x18.bibd.v1.IdentityRequest\x1a\x19.bibd.v1.IdentityResponse\x12E\n" +
	"\x0eUpdateIdentity\x12\x18.bibd.v1.IdentityRequest\x1a\x19.bibd.v1.IdentityResponse\x12U\n" +
	"\x12RetrieveIdentities\x12\x1e.bibd.v1.ListIdentitiesRequest\x1a\x1f.bibd.v1.ListIdentitiesResponseB3Z1github.com/bencoepp/bib/internal/pb/bibd/v1;bibv1b\x06proto3"

var (
	file_bibd_v1_identitiy_proto_rawDescOnce sync.Once
	file_bibd_v1_identitiy_proto_rawDescData []byte
)

func file_bibd_v1_identitiy_proto_rawDescGZIP() []byte {
	file_bibd_v1_identitiy_proto_rawDescOnce.Do(func() {
		file_bibd_v1_identitiy_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_bibd_v1_identitiy_proto_rawDesc), len(file_bibd_v1_identitiy_proto_rawDesc)))
	})
	return file_bibd_v1_identitiy_proto_rawDescData
}

var file_bibd_v1_identitiy_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_bibd_v1_identitiy_proto_goTypes = []any{
	(*IdentityRequest)(nil),        // 0: bibd.v1.IdentityRequest
	(*IdentityResponse)(nil),       // 1: bibd.v1.IdentityResponse
	(*ListIdentitiesRequest)(nil),  // 2: bibd.v1.ListIdentitiesRequest
	(*ListIdentitiesResponse)(nil), // 3: bibd.v1.ListIdentitiesResponse
}
var file_bibd_v1_identitiy_proto_depIdxs = []int32{
	1, // 0: bibd.v1.ListIdentitiesResponse.identities:type_name -> bibd.v1.IdentityResponse
	0, // 1: bibd.v1.IdentityService.RegisterIdentity:input_type -> bibd.v1.IdentityRequest
	0, // 2: bibd.v1.IdentityService.RetrieveIdentity:input_type -> bibd.v1.IdentityRequest
	0, // 3: bibd.v1.IdentityService.UpdateIdentity:input_type -> bibd.v1.IdentityRequest
	2, // 4: bibd.v1.IdentityService.RetrieveIdentities:input_type -> bibd.v1.ListIdentitiesRequest
	1, // 5: bibd.v1.IdentityService.RegisterIdentity:output_type -> bibd.v1.IdentityResponse
	1, // 6: bibd.v1.IdentityService.RetrieveIdentity:output_type -> bibd.v1.IdentityResponse
	1, // 7: bibd.v1.IdentityService.UpdateIdentity:output_type -> bibd.v1.IdentityResponse
	3, // 8: bibd.v1.IdentityService.RetrieveIdentities:output_type -> bibd.v1.ListIdentitiesResponse
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_bibd_v1_identitiy_proto_init() }
func file_bibd_v1_identitiy_proto_init() {
	if File_bibd_v1_identitiy_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_bibd_v1_identitiy_proto_rawDesc), len(file_bibd_v1_identitiy_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_bibd_v1_identitiy_proto_goTypes,
		DependencyIndexes: file_bibd_v1_identitiy_proto_depIdxs,
		MessageInfos:      file_bibd_v1_identitiy_proto_msgTypes,
	}.Build()
	File_bibd_v1_identitiy_proto = out.File
	file_bibd_v1_identitiy_proto_goTypes = nil
	file_bibd_v1_identitiy_proto_depIdxs = nil
}
