// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: bibd/v1/topic.proto

package bibv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TopicRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TopicRequest) Reset() {
	*x = TopicRequest{}
	mi := &file_bibd_v1_topic_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopicRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopicRequest) ProtoMessage() {}

func (x *TopicRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bibd_v1_topic_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopicRequest.ProtoReflect.Descriptor instead.
func (*TopicRequest) Descriptor() ([]byte, []int) {
	return file_bibd_v1_topic_proto_rawDescGZIP(), []int{0}
}

type TopicResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TopicResponse) Reset() {
	*x = TopicResponse{}
	mi := &file_bibd_v1_topic_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopicResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopicResponse) ProtoMessage() {}

func (x *TopicResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bibd_v1_topic_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopicResponse.ProtoReflect.Descriptor instead.
func (*TopicResponse) Descriptor() ([]byte, []int) {
	return file_bibd_v1_topic_proto_rawDescGZIP(), []int{1}
}

type ListTopicsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTopicsRequest) Reset() {
	*x = ListTopicsRequest{}
	mi := &file_bibd_v1_topic_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTopicsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTopicsRequest) ProtoMessage() {}

func (x *ListTopicsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bibd_v1_topic_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTopicsRequest.ProtoReflect.Descriptor instead.
func (*ListTopicsRequest) Descriptor() ([]byte, []int) {
	return file_bibd_v1_topic_proto_rawDescGZIP(), []int{2}
}

type ListTopicsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topics        []*TopicResponse       `protobuf:"bytes,1,rep,name=topics,proto3" json:"topics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTopicsResponse) Reset() {
	*x = ListTopicsResponse{}
	mi := &file_bibd_v1_topic_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTopicsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTopicsResponse) ProtoMessage() {}

func (x *ListTopicsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bibd_v1_topic_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTopicsResponse.ProtoReflect.Descriptor instead.
func (*ListTopicsResponse) Descriptor() ([]byte, []int) {
	return file_bibd_v1_topic_proto_rawDescGZIP(), []int{3}
}

func (x *ListTopicsResponse) GetTopics() []*TopicResponse {
	if x != nil {
		return x.Topics
	}
	return nil
}

var File_bibd_v1_topic_proto protoreflect.FileDescriptor

const file_bibd_v1_topic_proto_rawDesc = "" +
	"\n" +
	"\x13bibd/v1/topic.proto\x12\abibd.v1\"\x0e\n" +
	"\fTopicRequest\"\x0f\n" +
	"\rTopicResponse\"\x13\n" +
	"\x11ListTopicsRequest\"D\n" +
	"\x12ListTopicsResponse\x12.\n" +
	"\x06topics\x18\x01 \x03(\v2\x16.bibd.v1.TopicResponseR\x06topics2\x95\x02\n" +
	"\fTopicService\x12<\n" +
	"\vCreateTopic\x12\x15.bibd.v1.TopicRequest\x1a\x16.bibd.v1.TopicResponse\x12>\n" +
	"\rRetrieveTopic\x12\x15.bibd.v1.TopicRequest\x1a\x16.bibd.v1.TopicResponse\x12<\n" +
	"\vUpdateTopic\x12\x15.bibd.v1.TopicRequest\x1a\x16.bibd.v1.TopicResponse\x12I\n" +
	"\x0eRetrieveTopics\x12\x1a.bibd.v1.ListTopicsRequest\x1a\x1b.bibd.v1.ListTopicsResponseB3Z1github.com/bencoepp/bib/internal/pb/bibd/v1;bibv1b\x06proto3"

var (
	file_bibd_v1_topic_proto_rawDescOnce sync.Once
	file_bibd_v1_topic_proto_rawDescData []byte
)

func file_bibd_v1_topic_proto_rawDescGZIP() []byte {
	file_bibd_v1_topic_proto_rawDescOnce.Do(func() {
		file_bibd_v1_topic_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_bibd_v1_topic_proto_rawDesc), len(file_bibd_v1_topic_proto_rawDesc)))
	})
	return file_bibd_v1_topic_proto_rawDescData
}

var file_bibd_v1_topic_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_bibd_v1_topic_proto_goTypes = []any{
	(*TopicRequest)(nil),       // 0: bibd.v1.TopicRequest
	(*TopicResponse)(nil),      // 1: bibd.v1.TopicResponse
	(*ListTopicsRequest)(nil),  // 2: bibd.v1.ListTopicsRequest
	(*ListTopicsResponse)(nil), // 3: bibd.v1.ListTopicsResponse
}
var file_bibd_v1_topic_proto_depIdxs = []int32{
	1, // 0: bibd.v1.ListTopicsResponse.topics:type_name -> bibd.v1.TopicResponse
	0, // 1: bibd.v1.TopicService.CreateTopic:input_type -> bibd.v1.TopicRequest
	0, // 2: bibd.v1.TopicService.RetrieveTopic:input_type -> bibd.v1.TopicRequest
	0, // 3: bibd.v1.TopicService.UpdateTopic:input_type -> bibd.v1.TopicRequest
	2, // 4: bibd.v1.TopicService.RetrieveTopics:input_type -> bibd.v1.ListTopicsRequest
	1, // 5: bibd.v1.TopicService.CreateTopic:output_type -> bibd.v1.TopicResponse
	1, // 6: bibd.v1.TopicService.RetrieveTopic:output_type -> bibd.v1.TopicResponse
	1, // 7: bibd.v1.TopicService.UpdateTopic:output_type -> bibd.v1.TopicResponse
	3, // 8: bibd.v1.TopicService.RetrieveTopics:output_type -> bibd.v1.ListTopicsResponse
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_bibd_v1_topic_proto_init() }
func file_bibd_v1_topic_proto_init() {
	if File_bibd_v1_topic_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_bibd_v1_topic_proto_rawDesc), len(file_bibd_v1_topic_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_bibd_v1_topic_proto_goTypes,
		DependencyIndexes: file_bibd_v1_topic_proto_depIdxs,
		MessageInfos:      file_bibd_v1_topic_proto_msgTypes,
	}.Build()
	File_bibd_v1_topic_proto = out.File
	file_bibd_v1_topic_proto_goTypes = nil
	file_bibd_v1_topic_proto_depIdxs = nil
}
